# Generated by Django 6.0.5 on 2026-08-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='PICKUP', max_length=20),
        ),
    ]
