# Generated by Django 6.0.5 on 2026-09-09 14:04
import random

from django.db import migrations

# No 0/O/1/I — avoids confusion when an order number is read out over WhatsApp.
_ORDER_CODE_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('dashboard', 'Order')
    used = set(Order.objects.exclude(order_number=None).values_list('order_number', flat=True))

    for order in Order.objects.filter(order_number__isnull=True).order_by('created_at'):
        date_part = order.created_at.strftime('%m%d')
        for _ in range(10):
            suffix = ''.join(random.choices(_ORDER_CODE_CHARS, k=2))
            candidate = f'{date_part}-{suffix}'
            if candidate not in used:
                break
        else:
            candidate = f'{date_part}-{"".join(random.choices(_ORDER_CODE_CHARS, k=4))}'
        used.add(candidate)
        order.order_number = candidate
        order.save(update_fields=['order_number'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_order_order_number'),
    ]

    operations = [
        migrations.RunPython(backfill_order_numbers, noop_reverse),
    ]
