# Generated by Django 6.0.5 on 2026-09-09 14:25
from django.db import migrations, models


def backfill_pod_paid_status(apps, schema_editor):
    """Orders already marked COMPLETED + PAY_ON_DELIVERY had cash collected
    in reality, but nothing ever set payment_status=PAID for them (only the
    Squad webhook does, and that's transfer-only) — so they were invisible
    to revenue analytics. Use updated_at as a stand-in for when they were
    completed, since paid_at didn't exist yet at the time."""
    Order = apps.get_model('dashboard', 'Order')
    Order.objects.filter(
        status='COMPLETED',
        payment_method='PAY_ON_DELIVERY',
        payment_status='UNPAID',
    ).update(payment_status='PAID', paid_at=models.F('updated_at'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_backfill_order_number'),
    ]

    operations = [
        migrations.RunPython(backfill_pod_paid_status, noop_reverse),
    ]
