# Generated by Django 6.0.5 on 2026-09-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_backfill_pod_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='vendor_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='vendor_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
