# Generated by Django 6.0.5 on 2026-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_businesssettings_feedback_vendor_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='operating_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
