# Generated by Django 6.0.5 on 2026-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_businesssettings_accepting_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='notify_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='notify_order_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='notify_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='notify_tips_promos',
            field=models.BooleanField(default=False),
        ),
    ]
