# Generated by Django 6.0.5 on 2026-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_businesssettings_notify_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='notify_new_orders',
            field=models.BooleanField(default=True),
        ),
    ]
