# Generated by Django 6.0.5 on 2026-08-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botsession_notes_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='fulfillment_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
