# Generated by Django 6.0.5 on 2026-08-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botsession_fulfillment_type'),
        ('dashboard', '0004_order_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='pending_feedback_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.order'),
        ),
    ]
